version: '3.7'
services:
  paco-graph-api:
    build: .
    environment:
      - SERVER_PORT=8080
      - MONGODB_PORT=27017
      - MONGODB_DOMAIN=host.docker.internal
    ports:
      - '8080:8080'
    links:
      - mongo
  mongo:
    image: mongo
