version: '3.7'
services:
  paco-graph-api:
    build: .
    environment:
      - SERVER_PORT=8088
      - MONGODB_PORT=27017
      - MONGODB_DOMAIN=host.docker.internal
    ports:
      - '8080:8080'
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ~/paco-backend-graph-api/database/data/db:/data/db
